### ISSUE TITLE
Report # 1 | Database

### ISSUE THREAD

**Issue by XanezOficial** [XanezTech/Xanez#1]
**Initial problem**
There have been compatibility problems with the database.

**Description**
A leak has been identified in the stored data structures, which have caused forced reboots in the last few hours. But don't worry, it's already stirring.

**Affected resources**
All events and plugins in commands

**NOTE:** Possibly the data stored in the database will be deleted, and the events will be disabled until reaching a stable version

**Comment by itsjustkanz** [comment]
We are studying the situation and we are sorry for the inconvenience caused!
Please join our Discord server, to know any news or, failing that, you can follow this problem
